/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClassView;

import ClassBeans.tbl_CidadesBeans;
import ClassBeans.tbl_EmpresaBeans;
import ClassBeans.tbl_EstadoBeans;
import ClassDal.tbl_CidEst;
import ClassDal.tbl_EmpresaCad;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phelype
 */
public class ViewCadEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadEmpresa
     */
    public ViewCadEmpresa() {
        initComponents();
        ReadTable();
        jcbCidade.removeAllItems();
        jcbEstado.removeAllItems();
        jcbCidade.setEditable(true);
        jcbEstado.setEditable(true);
        tbl_CidEst cies = new tbl_CidEst();
        for (tbl_CidadesBeans cid : cies.Cidades()) {
            jcbCidade.setSelectedItem(null);
            jcbCidade.addItem(cid);
        }
        for (tbl_EstadoBeans est : cies.Estados()) {
            jcbEstado.setSelectedItem(null);
            jcbEstado.addItem(est);
        }

    }

    public void ReadTable() {
        DefaultTableModel table = (DefaultTableModel) jTableEmpresas.getModel();
        tbl_EmpresaCad cad = new tbl_EmpresaCad();
        table.setNumRows(0);
        for (tbl_EmpresaBeans emp : cad.TableEmpresas()) {
            table.addRow(new Object[]{
                emp.getId_emp(),
                emp.getNome_emp(),
                emp.getEnd_emp(),
                emp.getCid_emp(),
                emp.getEst_emp(),
                emp.getCep(),
                emp.getAtiva(),
                emp.getNum_tel(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        textRua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbCidade = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textCep = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        textTelefone = new javax.swing.JFormattedTextField();
        jCheckBoxTrue = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxfalse = new javax.swing.JCheckBox();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Empresas.");

        jLabel1.setText("Empresa.:");

        jLabel2.setText("Rua.:");

        jLabel3.setText("Cidade.:");

        jLabel4.setText("UF.:");

        jLabel5.setText("CEP.:");

        try {
            textCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Telefone.:");

        try {
            textTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jCheckBoxTrue.setText("Ativo");
        jCheckBoxTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTrueActionPerformed(evt);
            }
        });

        jLabel7.setText("Situação.:");

        jCheckBoxfalse.setText("Inativa");
        jCheckBoxfalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxfalseActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jTableEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código.:", "Empresa.:", "Rua.:", "Cidade.:", "Estado.:", "CEP.:", "Situação.:", "Telefone.:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpresasMouseClicked(evt);
            }
        });
        jTableEmpresas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableEmpresasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpresas);
        if (jTableEmpresas.getColumnModel().getColumnCount() > 0) {
            jTableEmpresas.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jcbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4))
                                .addComponent(textRua, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textCep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBoxTrue)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBoxfalse))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnCadastrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCancelar)
                            .addGap(148, 148, 148))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textRua, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textCep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBoxTrue)
                                .addComponent(jCheckBoxfalse))
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrar)
                            .addComponent(btnCancelar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(842, 317));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxfalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxfalseActionPerformed
        jCheckBoxTrue.setSelected(false);

    }//GEN-LAST:event_jCheckBoxfalseActionPerformed

    private void jCheckBoxTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTrueActionPerformed
        jCheckBoxfalse.setSelected(false);
    }//GEN-LAST:event_jCheckBoxTrueActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        tbl_EmpresaBeans emp = new tbl_EmpresaBeans();
        tbl_EmpresaCad cad = new tbl_EmpresaCad();
        if (textEmpresa.getText().equalsIgnoreCase("") || textRua.getText().equalsIgnoreCase("") || textCep.getText().equalsIgnoreCase("")
                || textTelefone.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Existem campos sem preencher. \n"
                    + "Revise os campos e tente nomvamente !");
        } else {
            emp.setNome_emp(textEmpresa.getText());
            emp.setEnd_emp(textRua.getText());
            emp.setCid_emp((tbl_CidadesBeans) jcbCidade.getSelectedItem());
            emp.setEst_emp((tbl_EstadoBeans) jcbEstado.getSelectedItem());
            emp.setCep(textCep.getText());
            if (jCheckBoxTrue.isSelected()) {
                emp.setAtiva(jCheckBoxTrue.getActionCommand());
            } else {
                emp.setAtiva(jCheckBoxfalse.getActionCommand());
            }
            emp.setNum_tel(textTelefone.getText());
            cad.CadastatroEmp(emp);
            
            ReadTable();
        }
            textEmpresa.setText("");
            textRua.setText("");
            String atv = "vazio";
            if(atv.equals("vazio")){
                jCheckBoxTrue.setSelected(false);
                jCheckBoxfalse.setSelected(false);
            }
            
            textCep.setText("");
            textTelefone.setText("");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jTableEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpresasMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableEmpresas.getModel();
        int i = jTableEmpresas.getSelectedRow();
        if (jTableEmpresas.getSelectedRow() != -1) {
            textEmpresa.setText(jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 1).toString());
            textRua.setText(jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 2).toString());

            Object cidade = (jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 3).toString());
            String cid = cidade.toString();
            jcbCidade.setSelectedItem(cid);

            Object estado = (jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 4).toString());
            String est = estado.toString();
            jcbEstado.setSelectedItem(est);

            textCep.setText((String) jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 5));
            String atv = model.getValueAt(i, 6).toString();
            if (atv.equals("True")) {
                jCheckBoxTrue.setSelected(true);
                jCheckBoxfalse.setSelected(false);
              
            }else{
                jCheckBoxfalse.setSelected(true);
                jCheckBoxTrue.setSelected(false);
            }
            textTelefone.setText(jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 7).toString());
        }
    }//GEN-LAST:event_jTableEmpresasMouseClicked

    private void jTableEmpresasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableEmpresasKeyReleased
        DefaultTableModel model = (DefaultTableModel) jTableEmpresas.getModel();
        if (jTableEmpresas.getSelectedRow() != -1) {
            textEmpresa.setText(jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 1).toString());
            textRua.setText(jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 2).toString());

            Object cidade = (jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 3).toString());
            String cid = cidade.toString();
            jcbCidade.setSelectedItem(cid);

            Object estado = (jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 4).toString());
            String est = estado.toString();
            jcbEstado.setSelectedItem(est);

            textCep.setText((String) jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 5));
            String atv = (String) model.getValueAt(jTableEmpresas.getSelectedRow(), 6).toString();
            if (atv.equals("True")) {
                jCheckBoxTrue.setSelected(true);
                jCheckBoxfalse.setSelected(false);
              
            }else{
                jCheckBoxfalse.setSelected(true);
                jCheckBoxTrue.setSelected(false);
            }
            textTelefone.setText(jTableEmpresas.getValueAt(jTableEmpresas.getSelectedRow(), 7).toString());
        }
    }//GEN-LAST:event_jTableEmpresasKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBoxTrue;
    private javax.swing.JCheckBox jCheckBoxfalse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresas;
    private javax.swing.JComboBox<Object> jcbCidade;
    private javax.swing.JComboBox<Object> jcbEstado;
    private javax.swing.JFormattedTextField textCep;
    private javax.swing.JTextField textEmpresa;
    private javax.swing.JTextField textRua;
    private javax.swing.JFormattedTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
